#define rad2deg(K) ((K)*(180.0/3.1415926535))
#define deg2rad(K) ((K)*(3.1415926535/180.0))
#define mm2inch(K) (K/25.4)
#define inch2mm(K) (K*25.4)
#define Min(X,Y) ((X) < (Y) ? (X) : (Y))
#define Max(X,Y) ((X) > (Y) ? (X) : (Y))
#define IsHigh(BIT,BYTE)    ((BYTE & (1<<BIT)) != 0)
#define IsLow(BIT,BYTE)     ((BYTE & (1<<BIT)) == 0)
#define SetBit(BIT,BYTE)     BYTE |= (1<<BIT)
#define ClearBit(BIT,BYTE)   BYTE &= ~(1<<BIT)
#define ABS(a)                ((a) < 0 ? ((a)*(-1.0)) : (a))
#define SIGN(x)               ((x)==0?0:(x)>0?1:-1)
#define SQR(x)                ((x)*(x))